PUBLISHING.md
packages/cli/src/utils.ts

Use a separate asset manifest with devnet bundlr

---

packages/core/src/validate/generated/releaseJsonMetadata.ts

This file was updated by:
```
cd packages/core
pnpm generate-types
```
and then copying the generated files (*.d.ts) to the source controlled name for them (*.ts)

`saga_features` is an optional field

---

packages/core/src/validate/index.ts
packages/core/src/validate/schemas/releaseJsonMetadata.json

Fix issue with media not being uploaded to Arweave

---

packages/cli/package.json
packages/cli/src/commands/create/app.ts
packages/cli/src/index.ts
packages/cli/src/utils.ts

A number off of things, including addressing #117

Quality of life improvements

---

packages/cli/src/index.ts
packages/cli/src/utils.ts

Prevent portal submissions on devnet or testnet

---

packages/core/src/create/release.ts
packages/core/src/validate/schemas/appJsonMetadata.json
packages/core/src/validate/schemas/publisherJsonMetadata.json
packages/core/src/validate/schemas/releaseJsonMetadata.json

Constrain all name fields to 32 chars so minting does not fail

---

packages/cli/src/utils.ts

This warns the developers to configure the locales correctly.

Add a warning message if locale list is over 25

---

packages/cli/src/commands/create/app.ts
packages/cli/src/commands/create/publisher.ts
packages/cli/src/commands/create/release.ts
packages/core/src/publish/attestation.ts

Verified on devnet (transactions successfully submitted, and via inspection of attestation payloads.

Fix blockhash race conditions

---

packages/cli/src/utils.ts

Need to ensure that it's not empty as well, as it is required field.

Ensure all edge cases for short_description are checked

---

packages/cli/src/CliUtils.ts
packages/cli/src/index.ts

Update Default RPC Url

---

docs/PUBLISHING.md
docs/SETUP.md
example/dapp-store/package.json

Small PR to move some files around provide default package.json file to the example CLI project.

Small developer ergonomics improvements

---

docs/PUBLISHING.md
docs/SETUP.md

Addresses:
- #176 
- #177 
- #175 
- #103 
- #189

Documentation updates

---

packages/cli/src/commands/publish/PublishCliSubmit.ts
packages/cli/src/commands/publish/PublishCliUpdate.ts

```
┌────────────────────── Publishing Estimates ───────────────────────┐
│                                                                   │
│   New app submissions take around 3-4 business days for review.   │
│                                                                   │
└───────────────────────────────────────────────────────────────────┘
```
```
┌─────────────────────── Publishing Estimates ───────────────────────┐
│                                                                    │
│   App update approvals take around 1-2 business days for review.   │
│                                                                    │
└────────────────────────────────────────────────────────────────────┘
```
Added new warnings for publishing timelines.

App review timeline.

---

packages/cli/src/CliSetup.ts
packages/cli/src/commands/create/CreateCliRelease.ts
packages/core/src/publish/PublishCoreUpdate.ts

1. Fix `publish update` command promise.
2. Bump retries to 8.
3. Remove `process.exit()` after each command.

Bump max retries.

---

packages/cli/src/CliSetup.ts
packages/cli/src/CliUtils.ts
packages/cli/src/commands/ValidateCommand.ts
packages/cli/src/commands/create/CreateCliApp.ts
packages/cli/src/commands/create/CreateCliPublisher.ts
packages/cli/src/commands/create/CreateCliRelease.ts

1. Add checks for package names between app and release.
2. Add retries for app and publisher release.

Restructure warning messages.

---

packages/cli/src/config/PublishDetails.ts
packages/cli/src/prebuild_schema/publishing_source.yaml

Update publishing source to include default 4 screenshots fillers.

Update requirements to include videos

---

packages/cli/src/CliSetup.ts
packages/cli/src/commands/ValidateCommand.ts
packages/cli/src/commands/create/CreateCliPublisher.ts
packages/cli/src/commands/create/CreateCliRelease.ts
packages/cli/src/commands/publish/PublishCliSubmit.ts
packages/cli/src/commands/publish/PublishCliUpdate.ts

Add null checks for new fields in config

---

packages/cli/src/config/PublishDetails.ts
packages/core/src/validate/CoreValidation.ts

Check unsupported abis.

---

package.json
packages/cli/package.json
packages/cli/src/commands/create/CreateCliApp.ts
packages/cli/src/commands/create/CreateCliPublisher.ts
packages/cli/src/commands/create/CreateCliRelease.ts
packages/cli/src/commands/utils.ts
patches/@solana__web3.js@1.92.1.patch
pnpm-lock.yaml

Improve Solana transactions send and confirm logic.

CLI: improve Solana transaction confirmations

---

packages/cli/bin/dapp-store.js
packages/cli/src/CliUtils.ts
packages/cli/src/commands/scaffolding/ScaffoldInit.ts
packages/cli/src/config/PublishDetails.ts
packages/core/src/validate/CoreValidation.ts

This was conflicting with node 22.

Remove experimental json module.

---

packages/cli/package.json
packages/cli/src/CliUtils.ts
packages/cli/src/upload/TurboStorageDriver.ts
packages/cli/src/upload/index.ts
pnpm-lock.yaml

migrates from Irys to Turbo for file uploads to Arys
- Added `TurboStorageDriver` with automatic balance management and retry logic
- Added automatic top-up functionality with configurable buffer percentage
- Added error handling with exponential backoff for network failures

migrate arweave to @ardrive/turbo-sdk
